export const config = {
	autoStartLoad: true,
	startPosition: -1,
	debug: false,
	capLevelOnFPSDrop: false,
	capLevelToPlayerSize: false,
	defaultAudioCodec: undefined,
	initialLiveManifestSize: 1,
	maxBufferLength: 30,
	maxMaxBufferLength: 600,
	backBufferLength: Infinity,
	frontBufferFlushThreshold: Infinity,
	maxBufferSize: 60 * 1000 * 1000,
	maxBufferHole: 0.5,
	highBufferWatchdogPeriod: 2,
	nudgeOffset: 0.1,
	nudgeMaxRetry: 3,
	maxFragLookUpTolerance: 0.25,
	liveSyncDurationCount: 3,
	liveMaxLatencyDurationCount: Infinity,
	liveDurationInfinity: false,
	preferManagedMediaSource: false,
	enableWorker: true,
	enableSoftwareAES: true,
	manifestLoadingTimeOut: 10000,
	manifestLoadingMaxRetry: 1,
	manifestLoadingRetryDelay: 1000,
	manifestLoadingMaxRetryTimeout: 64000,
	startLevel: undefined,
	levelLoadingTimeOut: 10000,
	levelLoadingMaxRetry: 4,
	levelLoadingRetryDelay: 1000,
	levelLoadingMaxRetryTimeout: 64000,
	fragLoadingTimeOut: 20000,
	fragLoadingMaxRetry: 6,
	fragLoadingRetryDelay: 1000,
	fragLoadingMaxRetryTimeout: 64000,
	startFragPrefetch: false,
	testBandwidth: true,
	progressive: false,
	lowLatencyMode: true,
	fpsDroppedMonitoringPeriod: 5000,
	fpsDroppedMonitoringThreshold: 0.2,
	appendErrorMaxRetry: 3,
	enableDateRangeMetadataCues: true,
	enableEmsgMetadataCues: true,
	enableID3MetadataCues: true,
	enableWebVTT: true,
	enableIMSC1: true,
	enableCEA708Captions: true,
	stretchShortVideoTrack: false,
	maxAudioFramesDrift: 1,
	forceKeyFrameOnDiscontinuity: true,
	abrEwmaFastLive: 3.0,
	abrEwmaSlowLive: 9.0,
	abrEwmaFastVoD: 3.0,
	abrEwmaSlowVoD: 9.0,
	abrEwmaDefaultEstimate: 500000,
	abrEwmaDefaultEstimateMax: 5000000,
	abrBandWidthFactor: 0.95,
	abrBandWidthUpFactor: 0.7,
	abrMaxWithRealBitrate: false,
	maxStarvationDelay: 4,
	maxLoadingDelay: 4,
	minAutoBitrate: 0,
	emeEnabled: false,
	licenseXhrSetup: undefined,
	drmSystems: {},
	drmSystemOptions: {},
	cmcd: undefined,
};

export const MEDIA_SOURCE =
	"https://d3ukqbhrqb4xnt.cloudfront.net/share_videos/6e95f9a732a74664a4982adf4b808500/e8ffab99-e494-495d-8b21-787e95f9672d/211115200114.m3u8";

// export const MEDIA_SOURCE = "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8";
